name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - 'env/**'
      - '**.md'
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # Sets default directory for all steps
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'  # Enables caching
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          pytest -v
        else
          echo "No tests found, skipping"
          exit 0
        fi
        
  deploy:
    needs: test
    if: success() || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Prevents hanging
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Render Deployment
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        echo "Triggering deployment for service $SERVICE_ID"
        
        response=$(curl -s -X POST \
          -H "Authorization: Bearer $RENDER_TOKEN" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -w "\nHTTP_STATUS:%{http_code}" \
          "https://api.render.com/v1/services/$SERVICE_ID/deploys")
        
        http_status=$(echo "$response" | grep "HTTP_STATUS:" | cut -d':' -f2)
        body=$(echo "$response" | sed '/HTTP_STATUS:/d')
        
        if [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ]; then
          echo "✅ Deployment triggered successfully!"
          echo "Response: $body"
        else
          echo "❌ Failed to trigger deployment (HTTP $http_status)"
          echo "Error details: $body"
          exit 1
        fi