name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - 'env/**'
      - '**.md'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        pip install pytest
    - name: Run tests
      run: |
        if [ -d "backend/tests" ]; then
          cd backend && pytest -v
        else
          echo "No tests found, skipping"
          exit 0
        fi
        
  deploy:
    needs: test
    if: success() || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Render
      uses: render-actions/simple-deploy@v1
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}